sudo: required
dist: trusty
language: cpp
notifications:
  email:
    on_success: change
    on_failure: change
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated cmake || brew upgrade cmake ; fi
  - git submodule update --init --recursive
script:
  - cmake --version
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON test
  - cat compile_commands.json
  - make
