language: cpp
notifications:
  email:
    on_success: change
    on_failure: change
sudo: required
dist: trusty
before_install:
  - git submodule update --init --recursive
compiler:
  - gcc
  - clang
script:
  - cmake --version
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON test
  - cat compile_commands.json
  - make
